[project]
name = "orcamento-qpa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "great-expectations>=1.5.4",
    "pytest>=8.4.1",
    "python-dateutil>=2.9.0.post0",
]
